version: '3'
services:
  rabbitmq:
    image: rabbitmq:alpine
    hostname: rabbitmq
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${QUEUE_USER}
      RABBITMQ_DEFAULT_PASS: ${QUEUE_PASSWORD}
    
    networks:
      - default
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
      - ./certs:/etc/rabbitmq/certs 
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "5671:5671"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 30s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G  # Adjust this limit as necessary
        reservations:
          memory: 256M  # Minimum memory to reserve
  producer:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: producer
    volumes:
      - ./certs:/etc/rabbitmq/certs
    env_file:
      - .env
    networks:
      - default
    ports:
      - "5000:5000"
      - "5555:5555"
networks:
  default:
    name: lab_2
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500
