rabbitmqctl list_queues name messages
exit
rabbitmqctl list_queues name messages messages_ready
exit
rabbitmqctl list_queues
sudo rabbitmqctl purge_queue sqlite_data
rabbitmqctl purge_queue sqlite_data
rabbitmqctl list_queues
exit
rabbitmqctl list_queues
rabbitmqctl list_queues
rabbitmqctl list_queues
rabbitmqctl purge_queue sqlite_data
rabbitmqctl list_queues
exit
rabbitmqctl list_queues
rabbitmqctl list_queues
rabbitmqctl list_queues
rabbitmqctl list_queues
rabbitmqctl list_queues
rabbitmqctl list_queues
rabbitmqctl list_queues
rabbitmqctl list_queues
exit
